import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import type { InferenceAdapter, Objective, Proposal, RepoObservation, FileChange } from '../types.js';
import { buildBuilderPrompt } from './prompts.js';
import { createLogger } from '../utils/logger.js';
import { generateId } from '../utils/id.js';

const logger = createLogger('Builder');

export class Builder {
  constructor(
    private adapter: InferenceAdapter,
    private model: string,
    private repoPath: string,
  ) {}

  async generateProposal(objective: Objective, observation: RepoObservation): Promise<Proposal> {
    try {
      const prompt = buildBuilderPrompt(objective, observation);
      const response = await this.adapter.complete({
        messages: [{ role: 'user', content: prompt }],
        model: this.model,
        temperature: 0.3,
        maxTokens: 2048,
      });

      const content = response.content ?? '';
      const jsonMatch = content.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        logger.warn('Builder returned no JSON, generating minimal proposal');
        return this.minimalProposal(objective);
      }

      const parsed = JSON.parse(jsonMatch[0]) as {
        description?: string;
        rationale?: string;
        changes?: Array<{ path: string; content: string }>;
      };

      const changes: FileChange[] = (parsed.changes ?? []).map(c => {
        const fullPath = join(this.repoPath, c.path);
        let previousContent: string | undefined;
        if (existsSync(fullPath)) {
          try { previousContent = readFileSync(fullPath, 'utf-8'); } catch {}
        }
        return { path: c.path, content: c.content, previousContent };
      });

      if (changes.length === 0) {
        return this.minimalProposal(objective);
      }

      return {
        id: generateId('prop'),
        objectiveId: objective.id,
        description: parsed.description ?? objective.description,
        changes,
        rationale: parsed.rationale ?? 'Generated by builder',
        createdAt: Date.now(),
      };
    } catch (err) {
      logger.warn('Builder failed, generating minimal proposal', err);
      return this.minimalProposal(objective);
    }
  }

  private minimalProposal(objective: Objective): Proposal {
    return {
      id: generateId('prop'),
      objectiveId: objective.id,
      description: `Minimal proposal for: ${objective.description}`,
      changes: [],
      rationale: 'Fallback: no changes (observation pass)',
      createdAt: Date.now(),
    };
  }
}
