import { InferenceAdapter, Objective, Proposal, FileChange } from '../types.js';
import { buildProposalPrompt } from '../planner/prompts.js';
import { RepoAdapter } from '../adapters/repo/index.js';
import { newId } from '../utils/id.js';
import { logger } from '../utils/logger.js';

export class Builder {
  constructor(private adapter: InferenceAdapter, private repo: RepoAdapter) {}

  async generateProposal(objective: Objective): Promise<Proposal> {
    const filesToRead = objective.targetFile
      ? [objective.targetFile, ...this.getRelatedFiles(objective.targetFile)]
      : ['src/calculator.ts', 'src/utils.ts', 'src/string-ops.ts'];

    const fileContents: Record<string, string> = {};
    for (const f of filesToRead) {
      try {
        fileContents[f] = await this.repo.readFile(f);
      } catch {
        // file doesn't exist, skip
      }
    }

    if (!Object.keys(fileContents).length) {
      return this.fallbackProposal(objective);
    }

    const prompt = buildProposalPrompt(objective, fileContents);

    try {
      const response = await this.adapter.complete({
        messages: [
          { role: 'system', content: 'You generate precise code changes. Return only valid JSON.' },
          { role: 'user', content: prompt },
        ],
        temperature: 0.3,
        maxTokens: 2048,
      });

      const content = response.content ?? '';
      const jsonMatch = content.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        const changes: FileChange[] = (parsed.changes ?? []).map((c: any) => ({
          path: c.path,
          content: c.content,
        }));

        if (changes.length > 0) {
          return {
            id: `prop-${newId()}`,
            objectiveId: objective.id,
            description: parsed.description ?? objective.description,
            changes,
            rationale: parsed.rationale ?? 'Generated by builder',
            createdAt: Date.now(),
          };
        }
      }
    } catch (err) {
      logger.warn('Builder LLM failed', err);
    }

    return this.fallbackProposal(objective);
  }

  private getRelatedFiles(targetFile: string): string[] {
    const base = targetFile.replace('src/', '').replace('.ts', '');
    return [`tests/${base}.test.ts`];
  }

  private fallbackProposal(objective: Objective): Proposal {
    return {
      id: `prop-${newId()}`,
      objectiveId: objective.id,
      description: `Skipped: no valid proposal generated for "${objective.description}"`,
      changes: [],
      rationale: 'Fallback: LLM unavailable or returned invalid output',
      createdAt: Date.now(),
    };
  }
}
